# Generated by Django 4.2.11 on 2024-04-02 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=30)),
                ('sets', models.PositiveIntegerField()),
                ('reps', models.CharField(max_length=20)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.workout')),
            ],
        ),
    ]
