# Generated by Django 4.2.11 on 2024-04-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
